language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
addons:
  apt:
    packages:
      - libpcap-dev
matrix:
  include:
    - os: osx
      language: generic
      install: brew install libpcap
    - os: linux
      dist: trusty
install:
  - pip install codecov
script:
  - python setup.py build
  - python setup.py bdist_wheel
  - pip install --pre --no-index --find-links dist/ pcapy
  - pushd tests && coverage run pcapytests.py && popd && codecov
