language: python
python: 2.7
addons:
  apt:
    packages:
      - libpcap-dev
matrix:
  include:
    - os: osx
      python: system
      install: brew install libpcap
    - os: linux
    - os: linux
      dist: trusty
script: pip install .
